services:
  postgres:
    image: postgres:16
    container_name: chatdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "55432:5432"   # ← ВАЖНО: другой порт
    volumes:
      - chatdb_data:/var/lib/postgresql/data

volumes:
  chatdb_data:
